channels:
- conda-forge

dependencies:
- python
- jupyterlab
- notebook >= 7
- numpy
- matplotlib # Not yet used

# Graph related
- networkx
- pydot
- graphviz
- pyvis

# More immutable types
- pyrsistent
- frozendict
- bidict

# MILP Interface and solvers
- pulp
- highs
- scip
# guorbi solver is installed from the gurobi channel
- gurobi::gurobi

# Jupyter extensions
- ipywidgets
- ipytone
- pythreejs
- ipycanvas

# To work with C++. Will change eventually.
- cxx-compiler # Installs g++ compiler
- cppyy

# To generate latex figures
- pylatex

# For awalipy
- cython
- cmake
# - gxx
# - graphviz

# Useful for working
- snakeviz
- jupytext
- mypy
- jupyterlab-lsp
- python-lsp-server
- ruff # (cf https://www.pyopensci.org/python-package-guide/package-structure-code/intro.html)

# pip librari dependencies
# Some libraries we're interested in only exist on pip, not on conda-forge.
# So we install as much of their dependencies as possible through conda beforehand.
# music21 pip dependencies
- chardet
- joblib
- jsonpickle
- more-itertools
- webcolors
- requests

# automata-lib[visual] dependencies
#- networkx #>=2.6.2
#- frozendict #>=2.3.4
- typing-extensions #>=4.5.0

- coloraide #>=1.8.2
- pygraphviz #>=1.10

- pip
- pip:
  - types-networkx # Needed to typecheck networkx with mypy
  - music21
  - automata-lib