import _cython_3_0_9
from typing import Any, ClassVar, overload
import awalipy

__reduce_cython__: _cython_3_0_9.cython_function_or_method
__setstate_cython__: _cython_3_0_9.cython_function_or_method
__test__: dict
__version__: str
accessible: _cython_3_0_9.cython_function_or_method
accessible_here: _cython_3_0_9.cython_function_or_method
accessible_states: _cython_3_0_9.cython_function_or_method
add: _cython_3_0_9.cython_function_or_method
add_eps_transition: _cython_3_0_9.cython_function_or_method
add_final: _cython_3_0_9.cython_function_or_method
add_here: _cython_3_0_9.cython_function_or_method
add_initial: _cython_3_0_9.cython_function_or_method
add_state: _cython_3_0_9.cython_function_or_method
add_transition: _cython_3_0_9.fused_cython_function
add_weight: _cython_3_0_9.cython_function_or_method
allow_eps_transition: _cython_3_0_9.cython_function_or_method
allow_eps_transition_here: _cython_3_0_9.cython_function_or_method
alphabet: _cython_3_0_9.cython_function_or_method
alphabets: _cython_3_0_9.cython_function_or_method
are_equivalent: _cython_3_0_9.cython_function_or_method
are_isomorphic: _cython_3_0_9.cython_function_or_method
aut_to_exp: _cython_3_0_9.cython_function_or_method
available_weightsets: _cython_3_0_9.cython_function_or_method
characteristic: _cython_3_0_9.cython_function_or_method
coaccessible: _cython_3_0_9.cython_function_or_method
coaccessible_here: _cython_3_0_9.cython_function_or_method
coaccessible_states: _cython_3_0_9.cython_function_or_method
complement: _cython_3_0_9.cython_function_or_method
complement_here: _cython_3_0_9.cython_function_or_method
complete: _cython_3_0_9.cython_function_or_method
complete_here: _cython_3_0_9.cython_function_or_method
compose: _cython_3_0_9.cython_function_or_method
concatenate: _cython_3_0_9.cython_function_or_method
concatenate_here: _cython_3_0_9.cython_function_or_method
constant_term: _cython_3_0_9.cython_function_or_method
copy: _cython_3_0_9.cython_function_or_method
coquotient: _cython_3_0_9.cython_function_or_method
coquotient_here: _cython_3_0_9.cython_function_or_method
del_state: _cython_3_0_9.cython_function_or_method
del_transition: _cython_3_0_9.fused_cython_function
derivation: _cython_3_0_9.cython_function_or_method
derived_term: _cython_3_0_9.cython_function_or_method
determinize: _cython_3_0_9.cython_function_or_method
determinize_here: _cython_3_0_9.cython_function_or_method
display: _cython_3_0_9.cython_function_or_method
domain: _cython_3_0_9.cython_function_or_method
dst_of: _cython_3_0_9.cython_function_or_method
enumerate: _cython_3_0_9.cython_function_or_method
eval: _cython_3_0_9.fused_cython_function
exp_to_aut: _cython_3_0_9.cython_function_or_method
expand: _cython_3_0_9.cython_function_or_method
factor: _cython_3_0_9.cython_function_or_method
factor_here: _cython_3_0_9.cython_function_or_method
final_states: _cython_3_0_9.cython_function_or_method
get_final_weight: _cython_3_0_9.cython_function_or_method
get_initial_weight: _cython_3_0_9.cython_function_or_method
get_state_name: _cython_3_0_9.cython_function_or_method
get_static_context: _cython_3_0_9.cython_function_or_method
get_transition: _cython_3_0_9.fused_cython_function
get_weightset: _cython_3_0_9.cython_function_or_method
has_letter: _cython_3_0_9.fused_cython_function
has_state: _cython_3_0_9.cython_function_or_method
has_transition: _cython_3_0_9.fused_cython_function
image: _cython_3_0_9.cython_function_or_method
images: _cython_3_0_9.cython_function_or_method
incoming: _cython_3_0_9.fused_cython_function
infiltration: _cython_3_0_9.cython_function_or_method
initial_states: _cython_3_0_9.cython_function_or_method
inverse: _cython_3_0_9.cython_function_or_method
is_accessible: _cython_3_0_9.cython_function_or_method
is_ambiguous: _cython_3_0_9.cython_function_or_method
is_coaccessible: _cython_3_0_9.cython_function_or_method
is_complete: _cython_3_0_9.cython_function_or_method
is_deterministic: _cython_3_0_9.cython_function_or_method
is_final: _cython_3_0_9.cython_function_or_method
is_functional: _cython_3_0_9.cython_function_or_method
is_initial: _cython_3_0_9.cython_function_or_method
is_proper: _cython_3_0_9.cython_function_or_method
is_synchronizable: _cython_3_0_9.cython_function_or_method
is_trim: _cython_3_0_9.cython_function_or_method
is_valid: _cython_3_0_9.cython_function_or_method
label_of: _cython_3_0_9.fused_cython_function
left_reduce: _cython_3_0_9.cython_function_or_method
list_examples: _cython_3_0_9.cython_function_or_method
lmul_weight: _cython_3_0_9.cython_function_or_method
load: _cython_3_0_9.cython_function_or_method
make_automaton: _cython_3_0_9.cython_function_or_method
make_cerny: _cython_3_0_9.cython_function_or_method
make_divkbaseb: _cython_3_0_9.cython_function_or_method
make_double_ring: _cython_3_0_9.cython_function_or_method
make_ladybird: _cython_3_0_9.cython_function_or_method
make_n_ultimate: _cython_3_0_9.cython_function_or_method
make_random_DFA: _cython_3_0_9.cython_function_or_method
make_transducer: _cython_3_0_9.cython_function_or_method
make_witness: _cython_3_0_9.cython_function_or_method
matrix_repr: _cython_3_0_9.cython_function_or_method
min_quotient: _cython_3_0_9.cython_function_or_method
minimal_automaton: _cython_3_0_9.cython_function_or_method
mult: _cython_3_0_9.cython_function_or_method
mult_here: _cython_3_0_9.cython_function_or_method
num_accessible_states: _cython_3_0_9.cython_function_or_method
num_coaccessible_states: _cython_3_0_9.cython_function_or_method
num_finals: _cython_3_0_9.cython_function_or_method
num_initials: _cython_3_0_9.cython_function_or_method
num_states: _cython_3_0_9.cython_function_or_method
num_tapes: _cython_3_0_9.cython_function_or_method
num_transitions: _cython_3_0_9.cython_function_or_method
num_useful_states: _cython_3_0_9.cython_function_or_method
outgoing: _cython_3_0_9.fused_cython_function
outin: _cython_3_0_9.fused_cython_function
partial_identity: _cython_3_0_9.cython_function_or_method
power: _cython_3_0_9.cython_function_or_method
power_here: _cython_3_0_9.cython_function_or_method
predecessors: _cython_3_0_9.fused_cython_function
prefix: _cython_3_0_9.cython_function_or_method
prefix_here: _cython_3_0_9.cython_function_or_method
product: _cython_3_0_9.cython_function_or_method
product_here: _cython_3_0_9.cython_function_or_method
projection: _cython_3_0_9.cython_function_or_method
proper: _cython_3_0_9.cython_function_or_method
proper_here: _cython_3_0_9.cython_function_or_method
py_callback_function: _cython_3_0_9.cython_function_or_method
quotient: _cython_3_0_9.cython_function_or_method
quotient_here: _cython_3_0_9.cython_function_or_method
reduce: _cython_3_0_9.cython_function_or_method
reduce_here: _cython_3_0_9.cython_function_or_method
right_reduce: _cython_3_0_9.cython_function_or_method
rmul_weight: _cython_3_0_9.cython_function_or_method
save: _cython_3_0_9.cython_function_or_method
scc_of: _cython_3_0_9.cython_function_or_method
sccs: _cython_3_0_9.cython_function_or_method
set_eps_transition: _cython_3_0_9.cython_function_or_method
set_final: _cython_3_0_9.cython_function_or_method
set_initial: _cython_3_0_9.cython_function_or_method
set_transition: _cython_3_0_9.fused_cython_function
set_weight: _cython_3_0_9.cython_function_or_method
shortest: _cython_3_0_9.cython_function_or_method
shuffle: _cython_3_0_9.cython_function_or_method
src_of: _cython_3_0_9.cython_function_or_method
standard: _cython_3_0_9.cython_function_or_method
star: _cython_3_0_9.cython_function_or_method
star_height: _cython_3_0_9.cython_function_or_method
star_here: _cython_3_0_9.cython_function_or_method
star_normal_form: _cython_3_0_9.cython_function_or_method
states: _cython_3_0_9.cython_function_or_method
successors: _cython_3_0_9.fused_cython_function
suffix: _cython_3_0_9.cython_function_or_method
suffix_here: _cython_3_0_9.cython_function_or_method
sum: _cython_3_0_9.cython_function_or_method
support: _cython_3_0_9.cython_function_or_method
synchronize: _cython_3_0_9.cython_function_or_method
thompson: _cython_3_0_9.cython_function_or_method
transitions: _cython_3_0_9.cython_function_or_method
transpose: _cython_3_0_9.cython_function_or_method
transpose_here: _cython_3_0_9.cython_function_or_method
trim: _cython_3_0_9.cython_function_or_method
trim_here: _cython_3_0_9.cython_function_or_method
union: _cython_3_0_9.cython_function_or_method
union_here: _cython_3_0_9.cython_function_or_method
unset_final: _cython_3_0_9.cython_function_or_method
unset_initial: _cython_3_0_9.cython_function_or_method
useful_states: _cython_3_0_9.cython_function_or_method
weight_of: _cython_3_0_9.cython_function_or_method

class Automaton(_BasicAutomaton):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def add_transition(self, *args, **kwargs): ...
    def allow_eps_transition(self, aut) -> Any: ...
    def allow_eps_transition_here(self) -> Any: ...
    def alphabet(self) -> Any: ...
    def are_equivalent(self, other) -> Any: ...
    def characteristic(self, weightset) -> Any: ...
    def complement(self) -> Any: ...
    def complement_here(self) -> Any: ...
    def complete(self) -> Any: ...
    def complete_here(self) -> Any: ...
    def coquotient(self, equiv) -> Any: ...
    def coquotient_here(self) -> Any: ...
    @overload
    def del_transition(self, tr_id) -> Any: ...
    @overload
    def del_transition(self, src, dst) -> Any: ...
    @overload
    def del_transition(self, src, dst, label) -> Any: ...
    def determinize(self, *args, **kwargs): ...
    def determinize_here(self, *args, **kwargs): ...
    def enumerate(self, max_len) -> Any: ...
    def eval(self, word) -> Any: ...
    def explore_by_length(self, length) -> Any: ...
    def explore_with_bound(self, weight) -> Any: ...
    def factor(self) -> Any: ...
    def factor_here(self) -> Any: ...
    def get_transition(self, *args, **kwargs): ...
    def has_letter(self, letter) -> Any: ...
    @overload
    def has_transition(self, tr_id) -> Any: ...
    @overload
    def has_transition(self, src, dst, label) -> Any: ...
    def incoming(self, *args, **kwargs): ...
    def infiltration(self, other) -> Any: ...
    def is_ambiguous(self, aut) -> Any: ...
    def is_complete(self) -> Any: ...
    def is_deterministic(self) -> Any: ...
    def is_eps_allowed(self) -> Any: ...
    def is_proper(self) -> Any: ...
    def is_valid(self) -> Any: ...
    def label_of(self, tr_id) -> Any: ...
    def left_reduce(self) -> Any: ...
    def matrix_repr(self) -> Any: ...
    def min_coquotient(self) -> Any: ...
    def min_quotient(self, *args, **kwargs): ...
    def minimal_automaton(self, *args, **kwargs): ...
    def null_state(self) -> Any: ...
    def null_transition(self, *args, **kwargs): ...
    def outgoing(self, *args, **kwargs): ...
    def partial_identity(self) -> Any: ...
    def power(self, n) -> Any: ...
    def power_here(self, n) -> Any: ...
    def predecessors(self, *args, **kwargs): ...
    def prefix(self) -> Any: ...
    def prefix_here(self) -> Any: ...
    def product(self, other) -> Any: ...
    def product_here(self, other) -> Any: ...
    def proper(self, *args, **kwargs): ...
    def proper_here(self, *args, **kwargs): ...
    def quotient(self, equiv) -> Any: ...
    @overload
    def quotient_here(self) -> Any: ...
    @overload
    def quotient_here(self, equiv) -> Any: ...
    def reduce(self) -> Any: ...
    def reduce_here(self, aut) -> Any: ...
    def right_reduce(self) -> Any: ...
    def set_transition(self, *args, **kwargs): ...
    def shortest(self, n) -> Any: ...
    def shuffle(self, other) -> Any: ...
    def successors(self, *args, **kwargs): ...
    def suffix(self) -> Any: ...
    def suffix_here(self) -> Any: ...
    def sum(self, other) -> Any: ...
    def sum_here(self, other) -> Any: ...
    def support(self) -> Any: ...
    def unpack_transition(self, tr_id) -> Any: ...
    def __call__(self, *args, **kwargs): ...
    def __reduce__(self): ...

class RatExp:
    ATOM: ClassVar[RatExpKind] = ...
    ONE: ClassVar[RatExpKind] = ...
    PROD: ClassVar[RatExpKind] = ...
    STAR: ClassVar[RatExpKind] = ...
    SUM: ClassVar[RatExpKind] = ...
    ZERO: ClassVar[RatExpKind] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def add(self, other_exp: RatExp) -> RatExp: ...
    def add_here(self, other_exp: RatExp) -> Any: ...
    def alphabet(self) -> str: ...
    def children(self) -> tuple[]: ...
    def constant_term(self) -> Any: ...
    def content(self) -> Any: ...
    def copy(self) -> Any: ...
    def derivation(self, *args, **kwargs): ...
    def display(self, *args, **kwargs): ...
    def exp_to_aut(self, *args, **kwargs): ...
    def expand(self) -> Any: ...
    def get_kind(self) -> Any: ...
    def get_weightset(self) -> Any: ...
    def height(self) -> Any: ...
    def is_valid(self) -> Any: ...
    def length(self) -> Any: ...
    def minimal_automaton(self, *args, **kwargs): ...
    def mult(self, other_re) -> Any: ...
    def mult_here(self, *args, **kwargs): ...
    def promote(self, weightset) -> Any: ...
    def size(self) -> Any: ...
    def star(self) -> Any: ...
    def star_height(self) -> Any: ...
    def star_here(self) -> Any: ...
    def star_normal_form(self) -> Any: ...
    def weight(self) -> Any: ...
    def __add__(self, other): ...
    def __invert__(self): ...
    def __radd__(self, other): ...
    def __reduce__(self): ...
    def __rxor__(self, other): ...
    def __xor__(self, other): ...

class RatExpKind:
    ATOM: ClassVar[RatExpKind] = ...
    ONE: ClassVar[RatExpKind] = ...
    PROD: ClassVar[RatExpKind] = ...
    STAR: ClassVar[RatExpKind] = ...
    SUM: ClassVar[RatExpKind] = ...
    ZERO: ClassVar[RatExpKind] = ...
    instances: ClassVar[list] = ...
    of: ClassVar[dict] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self, *args, **kwargs): ...
    def value(self, *args, **kwargs): ...
    def __int__(self) -> int: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...

class Transducer(_BasicAutomaton):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def add_transition(self, *args, **kwargs): ...
    def alphabets(self) -> Any: ...
    def compose(self, other_tdc) -> Any: ...
    @overload
    def del_transition(self, tr_num) -> Any: ...
    @overload
    def del_transition(self, src, dst) -> Any: ...
    @overload
    def del_transition(self, src, dst, labels) -> Any: ...
    def domain(self) -> Any: ...
    @overload
    def eval(self, tdc, word) -> Any: ...
    @overload
    def eval(self, tdc, exp) -> Any: ...
    @overload
    def eval(self, tdc, aut) -> Any: ...
    def get_transition(self, src_id, dst_id, labels) -> Any: ...
    def has_letter(self, letter, tape_num) -> Any: ...
    @overload
    def has_transition(self, tr_id) -> Any: ...
    @overload
    def has_transition(self, src, dst, labels) -> Any: ...
    def image(self, *args, **kwargs): ...
    def images(self, *args, **kwargs): ...
    def incoming(self, *args, **kwargs): ...
    def inverse(self) -> Any: ...
    def is_functional(self) -> Any: ...
    def is_synchronizable(self, *args, **kwargs): ...
    def label_of(self, tr_id) -> Any: ...
    def lift(self, *args, **kwargs): ...
    def num_tapes(self) -> Any: ...
    def outgoing(self, *args, **kwargs): ...
    def predecessors(self, *args, **kwargs): ...
    def projection(self, i) -> Any: ...
    def set_transition(self, *args, **kwargs): ...
    def successors(self, *args, **kwargs): ...
    def synchronize(self, *args, **kwargs): ...
    def unpack_transition(self, tr_id) -> Any: ...
    def __call__(self, *args, **kwargs): ...
    def __reduce__(self): ...

class WeightSet:
    def __init__(self, *args, **kwargs) -> None: ...
    def add(self, weight1, weight2) -> Any: ...
    def div(self, weight1, weight2) -> Any: ...
    def mul(self, weight1, weight2) -> Any: ...
    def one(self) -> Any: ...
    def zero(self) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class _BasicAutomaton:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def accessible(self) -> Any: ...
    def accessible_here(self) -> Any: ...
    def accessible_states(self) -> Any: ...
    def add_eps_transition(self, *args, **kwargs): ...
    def add_final(self, *args, **kwargs): ...
    def add_initial(self, *args, **kwargs): ...
    def add_state(self, *args, **kwargs): ...
    def add_weight(self, tr_id, extra_weight) -> Any: ...
    def aut_to_exp(self, *args, **kwargs): ...
    def coaccessible(self, *args, **kwargs): ...
    def coaccessible_here(self) -> Any: ...
    def coaccessible_states(self) -> Any: ...
    def concatenate(self, other) -> Any: ...
    def concatenate_here(self, *args, **kwargs): ...
    def condensation(self) -> Any: ...
    def copy(self) -> Any: ...
    def del_state(self, stt) -> Any: ...
    def del_transition(self, *args, **kwargs): ...
    def display(self, *args, **kwargs): ...
    def dst_of(self, tr_id) -> Any: ...
    def final_states(self) -> Any: ...
    def get_final_weight(self, stt) -> Any: ...
    def get_initial_weight(self, stt) -> Any: ...
    def get_state_by_name(self, name) -> Any: ...
    def get_state_name(self, stt_id) -> Any: ...
    def get_static_context(self) -> Any: ...
    def get_weightset(self) -> Any: ...
    def has_explicit_name(self, stt_id) -> Any: ...
    def has_state(self, stt_id) -> Any: ...
    def has_transition(self, tr_id) -> Any: ...
    def incoming(self, *args, **kwargs): ...
    def initial_states(self) -> Any: ...
    def is_accessible(self) -> Any: ...
    def is_coaccessible(self) -> Any: ...
    def is_final(self, stt) -> Any: ...
    def is_initial(self, stt) -> Any: ...
    def is_trim(self) -> Any: ...
    def lift(self) -> Any: ...
    def lift_here(self) -> Any: ...
    def lmul_weight(self, tr_id, weight_factor) -> Any: ...
    def num_accessible_states(self) -> Any: ...
    def num_coaccessible_states(self) -> Any: ...
    def num_finals(self) -> Any: ...
    def num_initials(self) -> Any: ...
    def num_states(self) -> Any: ...
    def num_transitions(self) -> Any: ...
    def num_useful_states(self) -> Any: ...
    def outgoing(self, *args, **kwargs): ...
    def outin(self, src_id, dst_id) -> Any: ...
    def predecessors(self, *args, **kwargs): ...
    def promote(self, weightset) -> Any: ...
    def rmul_weight(self, *args, **kwargs): ...
    def save(self, *args, **kwargs): ...
    def scc_of(self, stt) -> Any: ...
    def sccs(self) -> Any: ...
    def set_eps_transition(self, *args, **kwargs): ...
    def set_final(self, *args, **kwargs): ...
    def set_initial(self, *args, **kwargs): ...
    def set_state_name(self, stt_id, name) -> Any: ...
    def set_weight(self, tr_id, new_weight) -> Any: ...
    def src_of(self, tr_id) -> Any: ...
    def states(self) -> Any: ...
    def strip_history(self) -> Any: ...
    def successors(self, *args, **kwargs): ...
    def transitions(self) -> Any: ...
    def transpose(self) -> Any: ...
    def transpose_here(self) -> Any: ...
    def trim(self) -> Any: ...
    def trim_here(self) -> Any: ...
    def unset_final(self, stt) -> Any: ...
    def unset_initial(self, stt) -> Any: ...
    def useful_states(self, *args, **kwargs): ...
    def weight_of(self, tr_id) -> Any: ...
    def __reduce__(self): ...
